#!/usr/bin/env python3
"""One-shot migration for the Awesome Camouflage specialist remediation.

The migration keeps the existing schema-2 compatibility fields used by the rest
of CamoGED and adds a multi-axis Awesome/catalog layer.  New records are marked
``metadata-only`` unless a separate review has established a stronger status.
"""

from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
TODAY = "2026-07-13"


def load(name: str) -> dict:
    return yaml.safe_load((DATA / name).read_text(encoding="utf-8")) or {}


def dump(name: str, payload: dict) -> None:
    (DATA / name).write_text(
        yaml.safe_dump(payload, allow_unicode=True, sort_keys=False, width=100),
        encoding="utf-8",
    )


def slug_words(value: str) -> str:
    return value.replace("-", " ").replace("_", " ")


def infer_axes(entry: dict, dataset_modalities: dict[str, str]) -> None:
    task = entry.get("task", "application")
    perspective = entry.get("perspective", "ai")
    pillar = entry.get("pillar", "detection")
    entry.setdefault("resource_type", "survey" if task == "survey" else "paper")
    entry.setdefault("pillars", [pillar])
    entry.setdefault("tasks", [task])

    modalities: list[str] = []
    for dataset_id in entry.get("datasets") or []:
        modality = dataset_modalities.get(dataset_id)
        if modality and modality not in modalities:
            modalities.append(modality)
    if not modalities:
        modalities = ["video"] if task == "video-cod" else ["rgb"]
    entry.setdefault("modalities", modalities)

    if task in {"survey", "dataset", "application"} or pillar == "evaluation":
        supervision = ["not-applicable"]
    elif task in {"generation", "physical-adversarial", "digital-adversarial"}:
        supervision = ["optimization-based"]
    else:
        supervision = ["fully-supervised"]
    entry.setdefault("supervision", supervision)

    if perspective == "nature":
        contexts = ["biological", "wildlife"]
    elif perspective == "war":
        contexts = ["military"]
    elif perspective == "art":
        contexts = ["art-design", "cultural-history"]
    else:
        contexts = ["computer-vision"]
    entry.setdefault("contexts", contexts)

    if entry["resource_type"] == "survey":
        families = ["survey"]
    elif entry.get("domain") == "physical":
        families = ["physical-system"]
    else:
        families = ["deep-learning"]
    entry.setdefault("method_families", families)
    entry.setdefault("description", entry.get("notes") or f"{slug_words(task).title()} resource.")
    entry.setdefault("curated", False)
    entry.setdefault("curation_tier", "catalog")
    entry.setdefault("date_added", TODAY)
    entry.setdefault("discovery_status", "accepted")
    entry.setdefault("canonical_url", entry.get("paper"))


def record(
    *,
    item_id: str,
    title: str,
    authors: str | list[str],
    venue: str,
    year: int,
    pillar: str,
    domain: str,
    perspective: str,
    task: str,
    paper: str,
    description: str,
    resource_type: str = "paper",
    code: str | None = None,
    datasets: list[str] | None = None,
    publication_status: str = "published",
    pillars: list[str] | None = None,
    tasks: list[str] | None = None,
    modalities: list[str] | None = None,
    supervision: list[str] | None = None,
    method_families: list[str] | None = None,
    contexts: list[str] | None = None,
    curated: bool = True,
    curation_tier: str = "recommended",
    source_type: str = "primary",
) -> dict:
    return {
        "id": item_id,
        "title": title,
        "authors": authors,
        "venue": venue,
        "year": year,
        "pillar": pillar,
        "domain": domain,
        "perspective": perspective,
        "task": task,
        "paper": paper,
        "code": code,
        "datasets": datasets or [],
        "bibtex_key": None,
        "notes": description,
        "publication_status": publication_status,
        "source_type": source_type,
        "verification_status": "metadata-only",
        "last_verified": TODAY,
        "verified_by": "maintainer",
        "license": None,
        "resource_type": resource_type,
        "pillars": pillars or [pillar],
        "tasks": tasks or [task],
        "modalities": modalities or (["video"] if task == "video-cod" else ["rgb"]),
        "supervision": supervision or ["not-applicable"],
        "method_families": method_families or ["deep-learning"],
        "contexts": contexts or ["computer-vision"],
        "description": description,
        "curated": curated,
        "curation_tier": curation_tier,
        "date_added": TODAY,
        "discovery_status": "accepted",
        "canonical_url": paper,
    }


def dataset(
    *,
    item_id: str,
    name: str,
    modality: str,
    year: int,
    link: str,
    notes: str,
    size: str | None,
    split: str,
    annotation: str,
    task: str = "dataset",
    publication_status: str = "released",
) -> dict:
    return {
        "id": item_id,
        "name": name,
        "task": task,
        "modality": modality,
        "size": size,
        "split": split,
        "year": year,
        "link": link,
        "license": None,
        "bibtex_key": None,
        "notes": notes,
        "publication_status": publication_status,
        "verification_status": "metadata-only",
        "last_verified": TODAY,
        "verified_by": "maintainer",
        "license_status": "unknown",
        "annotation": annotation,
    }


papers_doc = load("papers.yaml")
datasets_doc = load("datasets.yaml")
papers = papers_doc.setdefault("papers", [])
datasets = datasets_doc.setdefault("datasets", [])

new_datasets = [
    dataset(
        item_id="cotd",
        name="COTD",
        modality="video",
        year=2024,
        link="https://github.com/openat25/HIPTrack-MLS",
        notes="Bounding-box benchmark for camouflaged object tracking.",
        size="200 sequences; approximately 80,000 frames",
        split="benchmark split provided upstream",
        annotation="video sequences with bounding-box tracking annotations",
    ),
    dataset(
        item_id="camotion",
        name="CAMotion",
        modality="video",
        year=2026,
        link="https://www.camotion.focuslab.net.cn",
        notes="Wild camouflaged moving-object benchmark with challenge attributes.",
        size=None,
        split="benchmark split provided upstream",
        annotation="video masks and challenge attributes as provided upstream",
    ),
    dataset(
        item_id="rcod-benchmark",
        name="RCOD Benchmark",
        modality="rgb",
        year=2025,
        link="https://github.com/zhimengXin/RCOD",
        notes="Bounding-box annotations derived from established COD segmentation datasets.",
        size="three converted COD benchmarks",
        split="train/test protocol provided upstream",
        annotation="class labels and bounding boxes",
    ),
    dataset(
        item_id="ovcod-d",
        name="OVCOD-D",
        modality="multimodal",
        year=2026,
        link="https://arxiv.org/abs/2603.26109",
        notes="Open-vocabulary camouflage benchmark with fine-grained text descriptions.",
        size=None,
        split="open-set protocol described in the paper",
        annotation="bounding boxes and fine-grained textual descriptions",
        publication_status="project-page",
    ),
    dataset(
        item_id="mmcsbench",
        name="MMCSBench",
        modality="multimodal",
        year=2025,
        link="https://neurips.cc/virtual/2025/poster/121542",
        notes="Fine-grained benchmark for large vision-language models in camouflage scenes.",
        size=None,
        split="benchmark protocol provided upstream",
        annotation="multimodal question-answering and camouflage-scene annotations",
        publication_status="project-page",
    ),
    dataset(
        item_id="usc12k",
        name="USC12K",
        modality="rgb",
        year=2025,
        link="https://github.com/ssecv/USCNet",
        notes="Unconstrained salient-and-camouflaged object benchmark.",
        size="approximately 12K images",
        split="train/test protocol provided upstream",
        annotation="salient/camouflaged object masks and scene labels",
    ),
    dataset(
        item_id="reftextcod",
        name="RefTextCOD",
        modality="multimodal",
        year=2025,
        link="https://github.com/Heartfirey/SCOUT",
        notes="Text-augmented semi-supervised camouflage dataset introduced with SCOUT.",
        size=None,
        split="protocol provided upstream",
        annotation="images, masks or partial labels, and text descriptions",
        publication_status="project-page",
    ),
]

existing_dataset_ids = {item.get("id") for item in datasets}
for item in new_datasets:
    if item["id"] not in existing_dataset_ids:
        datasets.append(item)
        existing_dataset_ids.add(item["id"])

modalities_by_dataset = {item["id"]: item.get("modality", "rgb") for item in datasets}
for item in papers:
    infer_axes(item, modalities_by_dataset)

# Correct the most important existing records so the curated view does not
# inherit the old single-axis classification mechanically.
overrides = {
    "xiao2024survey": {
        "resource_type": "survey",
        "pillars": ["generation", "detection", "evaluation"],
        "tasks": ["survey", "image-cod", "video-cod", "instance-cod"],
        "curated": True,
        "curation_tier": "core",
        "method_families": ["survey"],
        "description": "Broad modern survey of image/video COD, extended tasks, datasets, and metrics.",
    },
    "pang2024zoomnext": {
        "curated": True,
        "curation_tier": "core",
        "method_families": ["transformer", "multi-scale"],
        "description": "Representative unified architecture spanning image and video camouflage segmentation.",
    },
    "cheng2022implicit": {
        "curated": True,
        "curation_tier": "core",
        "method_families": ["temporal-model", "motion"],
    },
    "phycamo2025": {
        "curated": True,
        "curation_tier": "recommended",
        "method_families": ["physical-adversarial", "contrastive-learning"],
    },
    "troscianko2017quantifying": {
        "curated": True,
        "curation_tier": "core",
        "resource_type": "paper",
        "tasks": ["camouflage-assessment", "human-detection"],
        "method_families": ["human-study", "appearance-model"],
    },
    "toet2020review": {
        "curated": True,
        "curation_tier": "core",
        "resource_type": "survey",
        "pillars": ["evaluation"],
        "tasks": ["camouflage-assessment"],
        "method_families": ["survey", "human-study", "physical-measurement"],
    },
    "talas2017military": {
        "curated": True,
        "curation_tier": "recommended",
        "resource_type": "paper",
        "pillars": ["generation", "evaluation"],
        "tasks": ["military-camouflage", "historical-analysis"],
        "method_families": ["comparative-analysis", "visual-ecology"],
        "contexts": ["military", "biological", "cultural-history"],
    },
    "mmcamobj2024": {
        "curated": True,
        "curation_tier": "recommended",
        "tasks": ["dataset", "vision-language", "multimodal-evaluation"],
        "modalities": ["multimodal", "vision-language"],
    },
}
for item in papers:
    if item["id"] in overrides:
        item.update(overrides[item["id"]])

new_papers = [
    record(
        item_id="fan2021concealed",
        title="Concealed Object Detection",
        authors="Fan, Deng-Ping; Ji, Ge-Peng; Cheng, Ming-Ming; Shao, Ling",
        venue="IEEE TPAMI",
        year=2022,
        pillar="detection",
        domain="intelligent",
        perspective="ai",
        task="image-cod",
        paper="https://arxiv.org/abs/2102.10274",
        code="https://github.com/DengPingFan/SINet",
        datasets=["cod10k", "camo"],
        description="Systematic COD study introducing COD10K and the SINet search-identification baseline.",
        modalities=["rgb"],
        supervision=["fully-supervised"],
        method_families=["cnn", "bio-inspired", "coarse-to-fine"],
        contexts=["computer-vision", "wildlife"],
        curation_tier="core",
    ),
    record(
        item_id="mei2021pfnet",
        title="Camouflaged Object Segmentation with Distraction Mining",
        authors="Mei, Haiyang; Ji, Ge-Peng; Wei, Ziqi; Yang, Xin; Wei, Xiaopeng; Fan, Deng-Ping",
        venue="CVPR",
        year=2021,
        pillar="detection",
        domain="intelligent",
        perspective="ai",
        task="image-cod",
        paper="https://arxiv.org/abs/2104.10475",
        description="PFNet separates global positioning from progressive focus and distraction mining.",
        supervision=["fully-supervised"],
        method_families=["cnn", "coarse-to-fine", "bio-inspired"],
        curation_tier="core",
    ),
    record(
        item_id="pang2022zoomnet",
        title="Zoom In and Out: A Mixed-scale Triplet Network for Camouflaged Object Detection",
        authors="Pang, Youwei; Zhao, Xiaoqi; Xiang, Tian-Zhu; Zhang, Lihe; Lu, Huchuan",
        venue="CVPR",
        year=2022,
        pillar="detection",
        domain="intelligent",
        perspective="ai",
        task="image-cod",
        paper="https://arxiv.org/abs/2203.02688",
        code="https://github.com/lartpang/ZoomNet",
        description="Representative mixed-scale COD model with explicit zoom-in/zoom-out processing.",
        supervision=["fully-supervised"],
        method_families=["cnn", "multi-scale"],
        curation_tier="core",
    ),
    record(
        item_id="huang2023fspnet",
        title="Feature Shrinkage Pyramid for Camouflaged Object Detection with Transformers",
        authors="Huang, Zhou; Dai, Hang; Xiang, Tian-Zhu; Wang, Shuo; Chen, Huai-Xin; Qin, Jie; Xiong, Huan",
        venue="CVPR",
        year=2023,
        pillar="detection",
        domain="intelligent",
        perspective="ai",
        task="image-cod",
        paper="https://arxiv.org/abs/2303.14816",
        code="https://github.com/ZhouHuang23/FSPNet",
        description="Transformer COD architecture combining locality enhancement and a shrinkage-pyramid decoder.",
        supervision=["fully-supervised"],
        method_families=["transformer", "multi-scale"],
    ),
    record(
        item_id="xiao2024hcm",
        title="Concealed Object Segmentation with Hierarchical Coherence Modeling",
        authors="Xiao, Fengyang; Zhang, Pan; He, Chunming; Hu, Runze; Liu, Yutao",
        venue="arXiv",
        year=2024,
        pillar="detection",
        domain="intelligent",
        perspective="ai",
        task="image-cod",
        paper="https://arxiv.org/abs/2401.11767",
        publication_status="preprint",
        description="Cross-task COS model emphasizing intra-stage and cross-stage feature coherence.",
        supervision=["fully-supervised"],
        method_families=["transformer", "coherence-modeling"],
    ),
    record(
        item_id="sayem2026cod10kc",
        title="COD10K-C: Benchmarking Robustness of Camouflaged Object Detection Under Natural Image Corruptions",
        authors="Sayem, Arafat Hossain",
        venue="arXiv",
        year=2026,
        pillar="evaluation",
        domain="intelligent",
        perspective="ai",
        task="dataset",
        paper="https://arxiv.org/abs/2606.02603",
        publication_status="preprint",
        description="Recent corruption-robustness benchmark derived from COD10K; release status requires follow-up.",
        pillars=["evaluation", "detection"],
        tasks=["robustness", "dataset", "image-cod"],
        supervision=["not-applicable"],
        method_families=["benchmark", "robustness"],
        curated=False,
    ),
    record(
        item_id="lamdouar2020motion",
        title="Betrayed by Motion: Camouflaged Object Discovery via Motion Segmentation",
        authors="Lamdouar, Hala; Yang, Charig; Xie, Weidi; Zisserman, Andrew",
        venue="ACCV",
        year=2020,
        pillar="detection",
        domain="intelligent",
        perspective="nature",
        task="video-cod",
        paper="https://arxiv.org/abs/2011.11630",
        datasets=["moca-mask"],
        description="Foundational motion-driven video camouflage discovery work and source of the MoCA lineage.",
        modalities=["video"],
        supervision=["self-supervised"],
        method_families=["motion", "registration", "memory"],
        contexts=["wildlife", "computer-vision"],
        curation_tier="core",
    ),
    record(
        item_id="zhou2025camsam2",
        title="CamSAM2: Segment Anything Accurately in Camouflaged Videos",
        authors="Zhou, Yuli; Sun, Guolei; Li, Yawei; Fu, Yuqian; Benini, Luca; Konukoglu, Ender",
        venue="NeurIPS",
        year=2025,
        pillar="detection",
        domain="intelligent",
        perspective="ai",
        task="video-cod",
        paper="https://arxiv.org/abs/2503.19730",
        code="https://github.com/zhoustan/CamSAM2",
        datasets=["moca-mask"],
        description="SAM2 adaptation for camouflaged videos using object-aware fusion and prototype memory.",
        modalities=["video"],
        supervision=["prompt-based", "fully-supervised"],
        method_families=["foundation-model", "memory", "prompting"],
        curation_tier="core",
    ),
    record(
        item_id="guo2025zsvcos",
        title="ZS-VCOS: Zero-Shot Outperforms Supervised Video Camouflaged Object Segmentation",
        authors="Guo, Wenqi; Du, Shan",
        venue="arXiv",
        year=2025,
        pillar="detection",
        domain="intelligent",
        perspective="ai",
        task="video-cod",
        paper="https://arxiv.org/abs/2505.01431",
        code="https://github.com/weathon/vcos",
        datasets=["moca-mask"],
        publication_status="preprint",
        description="Zero-shot video pipeline combining optical flow, a vision-language model, and SAM2.",
        modalities=["video", "vision-language"],
        supervision=["zero-shot", "training-free"],
        method_families=["foundation-model", "vision-language", "motion"],
    ),
    record(
        item_id="guo2024cot",
        title="Camouflaged Object Tracking: A Benchmark",
        authors="Guo, Xiaoyu; Zhong, Pengzhi; Zhang, Hao; Huang, Defeng; Shao, Huikai; Zhao, Qijun; Li, Shuiwang",
        venue="arXiv",
        year=2024,
        pillar="evaluation",
        domain="intelligent",
        perspective="ai",
        task="application",
        paper="https://arxiv.org/abs/2408.13877",
        code="https://github.com/openat25/HIPTrack-MLS",
        datasets=["cotd"],
        publication_status="preprint",
        description="Introduces COTD and evaluates general trackers in camouflaged-object sequences.",
        pillars=["evaluation", "detection"],
        tasks=["tracking", "dataset"],
        modalities=["video"],
        supervision=["fully-supervised"],
        method_families=["tracking", "benchmark"],
    ),
    record(
        item_id="yao2026camotion",
        title="CAMotion: A High-Quality Benchmark for Camouflaged Moving Object Detection in the Wild",
        authors="Yao, Siyuan; Sun, Hao; Yu, Ruiqi; Jiang, Xiwei; Ren, Wenqi; Cao, Xiaochun",
        venue="arXiv",
        year=2026,
        pillar="evaluation",
        domain="intelligent",
        perspective="nature",
        task="dataset",
        paper="https://arxiv.org/abs/2604.08287",
        code="https://www.camotion.focuslab.net.cn",
        datasets=["camotion"],
        publication_status="preprint",
        description="Recent wild-video benchmark with motion and boundary challenge attributes.",
        pillars=["evaluation", "detection"],
        tasks=["video-cod", "dataset"],
        modalities=["video"],
        supervision=["not-applicable"],
        method_families=["benchmark"],
        contexts=["wildlife", "computer-vision"],
    ),
    record(
        item_id="pei2022osformer",
        title="OSFormer: One-Stage Camouflaged Instance Segmentation with Transformers",
        authors="Pei, Jialun; Cheng, Tianyang; Fan, Deng-Ping; Tang, He; Chen, Chuanbo; Van Gool, Luc",
        venue="ECCV",
        year=2022,
        pillar="detection",
        domain="intelligent",
        perspective="ai",
        task="instance-cod",
        paper="https://arxiv.org/abs/2207.02255",
        code="https://github.com/PJLallen/OSFormer",
        description="Representative one-stage transformer framework for camouflaged instance segmentation.",
        supervision=["fully-supervised"],
        method_families=["transformer", "instance-segmentation"],
        curation_tier="core",
    ),
    record(
        item_id="dong2023uqformer",
        title="A Unified Query-based Paradigm for Camouflaged Instance Segmentation",
        authors="Dong, Bo; Pei, Jialun; Gao, Rongrong; Xiang, Tian-Zhu; Wang, Shuo; Xiong, Huan",
        venue="arXiv",
        year=2023,
        pillar="detection",
        domain="intelligent",
        perspective="ai",
        task="instance-cod",
        paper="https://arxiv.org/abs/2308.07392",
        code="https://github.com/dongbo811/UQFormer",
        publication_status="preprint",
        description="Query-based joint instance-mask and boundary modeling for CIS.",
        supervision=["fully-supervised"],
        method_families=["transformer", "query-based", "instance-segmentation"],
    ),
    record(
        item_id="xin2025rcod",
        title="Toward Realistic Camouflaged Object Detection: Benchmarks and Method",
        authors="Xin, Zhimeng; Wu, Tianxu; Chen, Shiming; Ye, Shuo; Xie, Zijing; Zou, Yixiong; You, Xinge; Guo, Yufei",
        venue="arXiv",
        year=2025,
        pillar="detection",
        domain="intelligent",
        perspective="ai",
        task="application",
        paper="https://arxiv.org/abs/2501.07297",
        code="https://github.com/zhimengXin/RCOD",
        datasets=["rcod-benchmark"],
        publication_status="preprint",
        description="Defines bounding-box-oriented realistic COD and releases converted detection benchmarks.",
        tasks=["bbox-rcod", "dataset"],
        supervision=["fully-supervised"],
        method_families=["foundation-model", "object-detection"],
        curation_tier="core",
    ),
    record(
        item_id="vu2023ovdiffcis",
        title="Leveraging Open-Vocabulary Diffusion to Camouflaged Instance Segmentation",
        authors="Vu, Tuan-Anh; Nguyen, Duc Thanh; Guo, Qing; Hua, Binh-Son; Chung, Nhat Minh; Tsang, Ivor W.; Yeung, Sai-Kit",
        venue="arXiv",
        year=2023,
        pillar="detection",
        domain="intelligent",
        perspective="ai",
        task="instance-cod",
        paper="https://arxiv.org/abs/2312.17505",
        publication_status="preprint",
        description="Explores open-vocabulary diffusion priors for camouflaged instance segmentation.",
        tasks=["instance-cod", "open-vocabulary"],
        modalities=["rgb", "vision-language"],
        supervision=["zero-shot"],
        method_families=["diffusion", "open-vocabulary", "instance-segmentation"],
    ),
    record(
        item_id="lai2024camoteacher",
        title="CamoTeacher: Dual-Rotation Consistency Learning for Semi-Supervised Camouflaged Object Detection",
        authors="Lai, Xunfa; Yang, Zhiyu; Hu, Jie; Zhang, Shengchuan; Cao, Liujuan; Jiang, Guannan; Wang, Zhiyu; Zhang, Songan; Ji, Rongrong",
        venue="arXiv",
        year=2024,
        pillar="detection",
        domain="intelligent",
        perspective="ai",
        task="image-cod",
        paper="https://arxiv.org/abs/2408.08050",
        publication_status="preprint",
        description="Semi-supervised teacher-student COD with pixel- and instance-level rotation consistency.",
        tasks=["image-cod", "semi-supervised-cod"],
        supervision=["semi-supervised"],
        method_families=["teacher-student", "consistency-learning"],
        curation_tier="core",
    ),
    record(
        item_id="he2025see",
        title="Segment Concealed Objects with Incomplete Supervision",
        authors="He, Chunming; Li, Kai; Zhang, Yachao; Yang, Ziyun; Pang, Youwei; Tang, Longxiang; Fang, Chengyu; Zhang, Yulun; Kong, Linghe; Li, Xiu; Farsiu, Sina",
        venue="arXiv",
        year=2025,
        pillar="detection",
        domain="intelligent",
        perspective="ai",
        task="image-cod",
        paper="https://arxiv.org/abs/2506.08955",
        publication_status="preprint",
        description="Unified weak/semi-supervised COS framework using SAM-generated and quality-controlled pseudo-labels.",
        tasks=["image-cod", "weakly-supervised-cod", "semi-supervised-cod"],
        supervision=["weakly-supervised", "semi-supervised"],
        method_families=["foundation-model", "teacher-student", "pseudo-labeling"],
        curation_tier="core",
    ),
    record(
        item_id="mok2025hpgt",
        title="A Holistically Point-guided Text Framework for Weakly-Supervised Camouflaged Object Detection",
        authors="Mok, Tsui Qin; Gao, Shuyong; Xing, Haozhe; He, Miaoyang; Wang, Yan; Zhang, Wenqiang",
        venue="arXiv",
        year=2025,
        pillar="detection",
        domain="intelligent",
        perspective="ai",
        task="image-cod",
        paper="https://arxiv.org/abs/2501.06038",
        publication_status="preprint",
        description="Point- and text-guided weak supervision for COD.",
        tasks=["image-cod", "weakly-supervised-cod", "vision-language"],
        modalities=["rgb", "vision-language"],
        supervision=["weakly-supervised", "point-supervised"],
        method_families=["vision-language", "prompting", "weak-supervision"],
    ),
    record(
        item_id="yan2025ucoddpl",
        title="UCOD-DPL: Unsupervised Camouflaged Object Detection via Dynamic Pseudo-label Learning",
        authors="Yan, Weiqi; Chen, Lvhai; Kou, Huaijia; Zhang, Shengchuan; Zhang, Yan; Cao, Liujuan",
        venue="arXiv",
        year=2025,
        pillar="detection",
        domain="intelligent",
        perspective="ai",
        task="image-cod",
        paper="https://arxiv.org/abs/2506.07087",
        publication_status="preprint",
        description="Unsupervised teacher-student COD with adaptive pseudo-labeling and adversarial decoding.",
        tasks=["image-cod", "unsupervised-cod"],
        supervision=["unsupervised"],
        method_families=["teacher-student", "pseudo-labeling", "adversarial-learning"],
        curation_tier="core",
    ),
    record(
        item_id="yan2025scout",
        title="SCOUT: Semi-supervised Camouflaged Object Detection by Utilizing Text and Adaptive Data Selection",
        authors="Yan, Weiqi; Chen, Lvhai; Zhang, Shengchuan; Zhang, Yan; Cao, Liujuan",
        venue="arXiv",
        year=2025,
        pillar="detection",
        domain="intelligent",
        perspective="ai",
        task="image-cod",
        paper="https://arxiv.org/abs/2508.17843",
        code="https://github.com/Heartfirey/SCOUT",
        datasets=["reftextcod"],
        publication_status="preprint",
        description="Semi-supervised COD with adaptive data selection and text-visual interaction.",
        tasks=["image-cod", "semi-supervised-cod", "vision-language"],
        modalities=["rgb", "vision-language"],
        supervision=["semi-supervised"],
        method_families=["vision-language", "active-data-selection"],
    ),
    record(
        item_id="ni2026fclcod",
        title="FCL-COD: Weakly Supervised Camouflaged Object Detection with Frequency-aware and Contrastive Learning",
        authors="Ni, Jingchen; Zhang, Quan; Jiang, Dan; Lv, Keyu; Zhang, Ke; Yuan, Chun",
        venue="arXiv",
        year=2026,
        pillar="detection",
        domain="intelligent",
        perspective="ai",
        task="image-cod",
        paper="https://arxiv.org/abs/2603.22969",
        publication_status="preprint",
        description="Frequency-aware LoRA and contrastive learning for weakly supervised COD with SAM.",
        tasks=["image-cod", "weakly-supervised-cod"],
        supervision=["weakly-supervised"],
        method_families=["foundation-model", "parameter-efficient-tuning", "frequency-domain"],
    ),
    record(
        item_id="lei2025camf",
        title="Towards Real Zero-Shot Camouflaged Object Segmentation without Camouflaged Annotations",
        authors="Lei, Cheng; Fan, Jie; Li, Xinran; Xiang, Tian-Zhu; Li, Ao; Zhu, Ce; Zhang, Le",
        venue="IEEE TPAMI",
        year=2025,
        pillar="detection",
        domain="intelligent",
        perspective="ai",
        task="open-vocab-cos",
        paper="https://arxiv.org/abs/2410.16953",
        code="https://github.com/R-LEI360725/ZSCOS-CaMF",
        description="Real zero-shot COS framework combining masked-image pretraining, MLLM semantics, and PEFT.",
        tasks=["zero-shot-cod", "open-vocabulary", "image-cod"],
        modalities=["rgb", "vision-language"],
        supervision=["zero-shot"],
        method_families=["foundation-model", "vision-language", "parameter-efficient-tuning"],
        curation_tier="core",
    ),
    record(
        item_id="tang2023mmcpf",
        title="Chain of Visual Perception: Harnessing Multimodal Large Language Models for Zero-shot Camouflaged Object Detection",
        authors="Tang, Lv; Jiang, Peng-Tao; Shen, Zhihao; Zhang, Hao; Chen, Jinwei; Li, Bo",
        venue="arXiv",
        year=2023,
        pillar="detection",
        domain="intelligent",
        perspective="ai",
        task="foundation-model",
        paper="https://arxiv.org/abs/2311.11273",
        code="https://github.com/luckybird1994/MMCPF",
        description="Early MLLM-centered zero-shot camouflage perception pipeline using language and visual cues.",
        tasks=["zero-shot-cod", "vision-language", "video-cod", "image-cod"],
        modalities=["rgb", "video", "vision-language"],
        supervision=["zero-shot", "training-free"],
        method_families=["vision-language", "foundation-model", "chain-of-thought"],
    ),
    record(
        item_id="liang2026sddf",
        title="SDDF: Specificity-Driven Dynamic Focusing for Open-Vocabulary Camouflaged Object Detection",
        authors="Liang, Jiaming; Zhan, Yifeng; Liu, Chunlin; Zheng, Weihua; Peng, Bingye; Liang, Qiwei; Cai, Boyang; Mai, Xiaochun; Nie, Qiang",
        venue="arXiv",
        year=2026,
        pillar="detection",
        domain="intelligent",
        perspective="ai",
        task="open-vocab-cos",
        paper="https://arxiv.org/abs/2603.26109",
        datasets=["ovcod-d"],
        publication_status="preprint",
        description="Open-vocabulary bounding-box COD with specificity-aware text descriptions and OVCOD-D.",
        tasks=["open-vocabulary", "bbox-rcod", "dataset"],
        modalities=["rgb", "vision-language"],
        supervision=["zero-shot", "fully-supervised"],
        method_families=["open-vocabulary", "vision-language", "object-detection"],
        curation_tier="core",
    ),
    record(
        item_id="zhang2025mmcsbench",
        title="MMCSBench: A Fine-Grained Benchmark for Large Vision-Language Models in Camouflage Scenes",
        authors="Zhang, Jin; Zhang, Ruiheng; Cao, Zhe; Chen, Kaizheng",
        venue="NeurIPS",
        year=2025,
        pillar="evaluation",
        domain="intelligent",
        perspective="ai",
        task="dataset",
        paper="https://neurips.cc/virtual/2025/poster/121542",
        datasets=["mmcsbench"],
        description="Fine-grained benchmark for evaluating LVLM reasoning and perception in camouflage scenes.",
        tasks=["vision-language", "multimodal-evaluation", "dataset"],
        modalities=["multimodal", "vision-language"],
        supervision=["not-applicable"],
        method_families=["benchmark", "vision-language"],
    ),
    record(
        item_id="zhou2025uscnet",
        title="Rethinking Detecting Salient and Camouflaged Objects in Unconstrained Scenes",
        authors="Zhou, Zhangjun; Li, Yiping; Zhong, Chunlin; Huang, Jianuo; Pei, Jialun; Li, Hua; Tang, He",
        venue="ICCV",
        year=2025,
        pillar="detection",
        domain="intelligent",
        perspective="ai",
        task="image-cod",
        paper="https://arxiv.org/abs/2412.10943",
        code="https://github.com/ssecv/USCNet",
        datasets=["usc12k"],
        description="Unifies salient and camouflaged object segmentation in unconstrained scenes.",
        tasks=["image-cod", "universal-segmentation", "dataset"],
        supervision=["fully-supervised"],
        method_families=["universal-segmentation", "transformer"],
    ),
    record(
        item_id="huang2019upc",
        title="Universal Physical Camouflage Attacks on Object Detectors",
        authors="Huang, Lifeng; Gao, Chengying; Zhou, Yuyin; Xie, Cihang; Yuille, Alan; Zou, Changqing; Liu, Ning",
        venue="CVPR",
        year=2020,
        pillar="generation",
        domain="physical",
        perspective="ai",
        task="physical-adversarial",
        paper="https://arxiv.org/abs/1909.04326",
        code="https://mesunhlf.github.io/index_physical.html",
        description="Foundational category-level physical camouflage attack and controlled AttackScenes benchmark.",
        tasks=["physical-adversarial", "generation"],
        modalities=["rgb"],
        supervision=["optimization-based"],
        method_families=["physical-adversarial", "rendering", "robust-optimization"],
        contexts=["computer-vision", "physical-system"],
        curation_tier="core",
    ),
    record(
        item_id="lamdouar2023makingbreaking",
        title="The Making and Breaking of Camouflage",
        authors="Lamdouar, Hala; Xie, Weidi; Zisserman, Andrew",
        venue="ICCV",
        year=2023,
        pillar="evaluation",
        domain="intelligent",
        perspective="nature",
        task="generation",
        paper="https://arxiv.org/abs/2309.03899",
        datasets=["moca-mask"],
        description="Links camouflage-effectiveness scores, synthetic generation, and video segmentation.",
        pillars=["evaluation", "generation", "detection"],
        tasks=["camouflage-assessment", "generation", "video-cod"],
        modalities=["rgb", "video"],
        supervision=["fully-supervised", "generative"],
        method_families=["assessment", "generation", "transformer"],
        contexts=["wildlife", "computer-vision"],
        curation_tier="core",
    ),
    record(
        item_id="cott1940adaptive",
        title="Adaptive Coloration in Animals",
        authors="Cott, Hugh B.",
        venue="Oxford University Press",
        year=1940,
        pillar="generation",
        domain="physical",
        perspective="nature",
        task="application",
        paper="https://archive.org/details/adaptivecolorati00cott",
        description="Foundational natural-history synthesis of concealment, disguise, disruption, and display.",
        resource_type="book",
        pillars=["generation", "evaluation"],
        tasks=["biological-camouflage", "historical-analysis"],
        modalities=["rgb"],
        supervision=["not-applicable"],
        method_families=["natural-history", "visual-ecology"],
        contexts=["biological", "wildlife", "military"],
        curation_tier="core",
        source_type="official-project",
    ),
    record(
        item_id="stevens2011animal",
        title="Animal Camouflage: Mechanisms and Function",
        authors="Stevens, Martin; Merilaita, Sami (eds.)",
        venue="Cambridge University Press",
        year=2011,
        pillar="evaluation",
        domain="physical",
        perspective="nature",
        task="survey",
        paper="https://www.cambridge.org/core/books/animal-camouflage/",
        description="Authoritative edited volume on mechanisms, evolution, perception, and experimental study of animal camouflage.",
        resource_type="book",
        pillars=["generation", "evaluation"],
        tasks=["biological-camouflage", "human-detection", "survey"],
        modalities=["rgb", "multispectral"],
        supervision=["not-applicable"],
        method_families=["visual-ecology", "behavioral-experiment", "survey"],
        contexts=["biological", "wildlife"],
        curation_tier="core",
        source_type="official-project",
    ),
    record(
        item_id="cuthill2019camouflage",
        title="Camouflage",
        authors="Cuthill, Innes C.",
        venue="Journal of Zoology",
        year=2019,
        pillar="evaluation",
        domain="physical",
        perspective="nature",
        task="survey",
        paper="https://doi.org/10.1111/jzo.12682",
        description="Modern visual-ecology review of camouflage mechanisms, evidence, and observer dependence.",
        resource_type="survey",
        pillars=["generation", "evaluation"],
        tasks=["biological-camouflage", "survey"],
        modalities=["rgb", "multispectral"],
        supervision=["not-applicable"],
        method_families=["visual-ecology", "survey"],
        contexts=["biological", "wildlife"],
        curation_tier="core",
    ),
    record(
        item_id="thayer1909concealing",
        title="Concealing-Coloration in the Animal Kingdom",
        authors="Thayer, Gerald H.; Thayer, Abbott H.",
        venue="Macmillan",
        year=1909,
        pillar="generation",
        domain="physical",
        perspective="art",
        task="application",
        paper="https://archive.org/details/concealingcolora00thay",
        description="Historically influential, controversial account of countershading and disruptive coloration.",
        resource_type="historical-source",
        pillars=["generation", "evaluation"],
        tasks=["biological-camouflage", "art-design", "historical-analysis"],
        modalities=["rgb"],
        supervision=["not-applicable"],
        method_families=["natural-history", "art-theory"],
        contexts=["biological", "art-design", "military", "cultural-history"],
        curation_tier="core",
        source_type="official-project",
    ),
    record(
        item_id="forbes2009dazzled",
        title="Dazzled and Deceived: Mimicry and Camouflage",
        authors="Forbes, Peter",
        venue="Yale University Press",
        year=2009,
        pillar="evaluation",
        domain="physical",
        perspective="nature",
        task="survey",
        paper="https://yalebooks.yale.edu/book/9780300178968/dazzled-and-deceived/",
        description="Cross-domain history connecting evolutionary mimicry, animal camouflage, and military practice.",
        resource_type="book",
        pillars=["generation", "evaluation"],
        tasks=["biological-camouflage", "military-camouflage", "historical-analysis"],
        modalities=["rgb"],
        supervision=["not-applicable"],
        method_families=["history-of-science", "survey"],
        contexts=["biological", "military", "cultural-history"],
        curation_tier="recommended",
        source_type="official-project",
    ),
    record(
        item_id="behrens2002falsecolors",
        title="False Colors: Art, Design and Modern Camouflage",
        authors="Behrens, Roy R.",
        venue="Bobolink Books",
        year=2002,
        pillar="generation",
        domain="physical",
        perspective="art",
        task="application",
        paper="https://works.bepress.com/roy-behrens/",
        description="Core art-and-design history of modern camouflage and its Gestalt and military connections.",
        resource_type="book",
        pillars=["generation", "evaluation"],
        tasks=["art-design", "military-camouflage", "historical-analysis"],
        modalities=["rgb"],
        supervision=["not-applicable"],
        method_families=["art-history", "design-history", "gestalt"],
        contexts=["art-design", "military", "cultural-history"],
        curation_tier="core",
        source_type="official-project",
    ),
    record(
        item_id="behrens2009camoupedia",
        title="Camoupedia: A Compendium of Research on Art, Architecture, and Camouflage",
        authors="Behrens, Roy R.",
        venue="Bobolink Books",
        year=2009,
        pillar="evaluation",
        domain="physical",
        perspective="art",
        task="survey",
        paper="https://camoupedia.blogspot.com/",
        description="Reference compendium covering art, architecture, perception, and military camouflage history.",
        resource_type="book",
        pillars=["generation", "evaluation"],
        tasks=["art-design", "military-camouflage", "historical-analysis", "survey"],
        modalities=["rgb"],
        supervision=["not-applicable"],
        method_families=["reference-work", "art-history"],
        contexts=["art-design", "military", "cultural-history"],
        curation_tier="recommended",
        source_type="official-project",
    ),
    record(
        item_id="hartcup1980camouflage",
        title="Camouflage: A History of Concealment and Deception in War",
        authors="Hartcup, Guy",
        venue="David & Charles",
        year=1980,
        pillar="evaluation",
        domain="physical",
        perspective="war",
        task="application",
        paper="https://search.worldcat.org/search?q=ti%3ACamouflage%20au%3AGuy%20Hartcup",
        description="Military history of concealment and deception technologies through the twentieth century.",
        resource_type="book",
        pillars=["generation", "evaluation"],
        tasks=["military-camouflage", "historical-analysis"],
        modalities=["rgb"],
        supervision=["not-applicable"],
        method_families=["military-history"],
        contexts=["military", "cultural-history"],
        curation_tier="core",
        source_type="secondary",
    ),
    record(
        item_id="nist2023aml",
        title="Adversarial Machine Learning: A Taxonomy and Terminology of Attacks and Mitigations",
        authors="NIST",
        venue="NIST AI 100-2e2023",
        year=2023,
        pillar="evaluation",
        domain="digital",
        perspective="ai",
        task="digital-adversarial",
        paper="https://csrc.nist.gov/pubs/ai/100/2/e2023/final",
        description="Authoritative terminology standard for adversarial-ML threats and mitigations used to bound digital/physical camouflage claims.",
        resource_type="standard",
        pillars=["generation", "detection", "evaluation"],
        tasks=["digital-adversarial", "physical-adversarial", "standard"],
        modalities=["multimodal"],
        supervision=["not-applicable"],
        method_families=["standard", "risk-taxonomy"],
        contexts=["computer-vision", "ai-safety"],
        curation_tier="recommended",
        source_type="primary",
    ),
]

existing_paper_ids = {item.get("id") for item in papers}
for item in new_papers:
    if item["id"] not in existing_paper_ids:
        papers.append(item)
        existing_paper_ids.add(item["id"])

# Stable human-curated order for the concise Awesome view.  The complete web
# catalog still renders every accepted metadata record.
awesome_config = {
    "schema_version": "1.0",
    "title": "Awesome Camouflage",
    "scope_note": (
        "Human-curated entry points across camouflage vision, biological camouflage, "
        "military history, art/design, generation, and assessment. The complete catalog "
        "is generated separately and may contain metadata-only records."
    ),
    "coverage_through": TODAY,
    "last_human_review": TODAY,
    "automated_discovery": {
        "workflow": ".github/workflows/awesome-discovery.yml",
        "status_surface": "GitHub issues labeled awesome:triage",
        "policy": "automated discovery, human acceptance",
    },
    "core_reading": [
        "cott1940adaptive",
        "stevens2011animal",
        "cuthill2019camouflage",
        "fan2021concealed",
        "xiao2024survey",
        "troscianko2017quantifying",
        "toet2020review",
        "behrens2002falsecolors",
        "hartcup1980camouflage",
    ],
    "sections": [
        {
            "id": "foundations",
            "title": "Foundations, surveys, and reading maps",
            "match": {"resource_type": ["survey", "book", "standard"]},
        },
        {"id": "image-cod", "title": "Image camouflaged object segmentation", "match": {"tasks": ["image-cod"]}},
        {"id": "video-tracking", "title": "Video segmentation and tracking", "match": {"tasks": ["video-cod", "tracking"]}},
        {"id": "instance-box-language", "title": "Instance, box, referring, and collaborative tasks", "match": {"tasks": ["instance-cod", "bbox-rcod", "referring-cod", "collaborative-cod"]}},
        {"id": "incomplete-supervision", "title": "Weak, semi, self, and unsupervised learning", "match": {"supervision": ["weakly-supervised", "semi-supervised", "self-supervised", "unsupervised"]}},
        {"id": "zero-open-foundation", "title": "Zero-shot, open-vocabulary, and foundation models", "match": {"tasks": ["zero-shot-cod", "open-vocabulary", "vision-language"], "method_families": ["foundation-model", "vision-language"]}},
        {"id": "multimodal", "title": "Depth, thermal, spectral, polarization, and multimodal camouflage", "match": {"modalities": ["depth", "thermal", "multispectral", "hyperspectral", "polarization", "multimodal", "vision-language"]}},
        {"id": "generation", "title": "Camouflage generation and adversarial camouflage", "match": {"pillars": ["generation"]}},
        {"id": "assessment", "title": "Assessment, metrics, human perception, and robustness", "match": {"tasks": ["camouflage-assessment", "human-detection", "robustness"], "pillars": ["evaluation"]}},
        {"id": "natural", "title": "Natural camouflage and visual ecology", "match": {"contexts": ["biological", "wildlife"]}},
        {"id": "military-art", "title": "Military history, art, architecture, and design", "match": {"contexts": ["military", "art-design", "cultural-history"]}},
    ],
    "external_candidate_sources": [
        "https://github.com/visionxiang/awesome-camouflaged-object-detection",
        "https://github.com/ChunmingHe/awesome-concealed-object-segmentation",
        "https://github.com/clelouch/Awesome-Camouflaged-Object-Detection",
        "https://github.com/GuoleiSun/Awesome-SAM2",
    ],
}

discovery_queries = {
    "schema_version": "1.0",
    "policy": "Candidate discovery only. No query may write directly to the accepted catalog.",
    "sources": {
        "arxiv": {"endpoint": "https://export.arxiv.org/api/query", "max_results_per_query": 25, "polite_delay_seconds": 3},
        "crossref": {"endpoint": "https://api.crossref.org/works", "max_enrichment_requests": 20},
    },
    "queries": [
        {"id": "image-cod", "source": "arxiv", "query": 'all:"camouflaged object detection" OR all:"concealed object segmentation"', "tags": ["image-cod"]},
        {"id": "video-cod", "source": "arxiv", "query": 'all:"video camouflaged object" OR all:"camouflaged moving object"', "tags": ["video-cod"]},
        {"id": "instance-box", "source": "arxiv", "query": 'all:"camouflaged instance segmentation" OR all:"realistic camouflaged object detection"', "tags": ["instance-cod", "bbox-rcod"]},
        {"id": "incomplete-supervision", "source": "arxiv", "query": '(all:camouflaged OR all:concealed) AND (all:"weakly supervised" OR all:"semi-supervised" OR all:unsupervised)', "tags": ["weakly-supervised-cod", "semi-supervised-cod", "unsupervised-cod"]},
        {"id": "zero-open", "source": "arxiv", "query": '(all:camouflaged OR all:concealed) AND (all:"zero-shot" OR all:"open-vocabulary")', "tags": ["zero-shot-cod", "open-vocabulary"]},
        {"id": "foundation-vlm", "source": "arxiv", "query": '(all:camouflaged OR all:concealed) AND (all:SAM OR all:"vision-language" OR all:MLLM)', "tags": ["foundation-model", "vision-language"]},
        {"id": "spectral", "source": "arxiv", "query": '(all:camouflaged OR all:camouflage) AND (all:multispectral OR all:hyperspectral OR all:polarization OR all:thermal)', "tags": ["multimodal"]},
        {"id": "generation", "source": "arxiv", "query": 'all:"camouflage generation" OR all:"adversarial camouflage"', "tags": ["generation", "physical-adversarial"]},
        {"id": "assessment", "source": "arxiv", "query": '(all:camouflage OR all:camouflaged) AND (all:assessment OR all:detectability OR all:"visual search")', "tags": ["camouflage-assessment"]},
        {"id": "tracking", "source": "arxiv", "query": 'all:"camouflaged object tracking"', "tags": ["tracking"]},
        {"id": "biology", "source": "crossref", "query": 'animal camouflage visual ecology detectability', "tags": ["biological-camouflage"]},
        {"id": "military-art", "source": "crossref", "query": 'military camouflage art design assessment', "tags": ["military-camouflage", "art-design"]},
    ],
}

dump("papers.yaml", papers_doc)
dump("datasets.yaml", datasets_doc)
dump("awesome.yaml", awesome_config)
dump("discovery_queries.yaml", discovery_queries)
print(f"Awesome migration complete: {len(papers)} resources, {len(datasets)} datasets")
